services:
  devpi:
    build: .
    image: devpi-server:latest
    container_name: devpi-server
    ports:
      - "3141:3141"
    volumes:
      - devpi_data:/data
    environment:
      - SERVERDIR=/data
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx:
    image: nginx:alpine
    container_name: devpi-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
     - devpi
    restart: unless-stopped

volumes:
  devpi_data:
